name: Deploy static site

on:
  push:
    branches:
      - main  # replace with your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs  # make sure npm build outputs here

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
